"""Tests for the rename-over-target deploy helpers and the ``build()`` wire-up.

After iteration 4, ``build()`` has a single deploy path: build to a sibling
.staging dir, apply ACLs, per-file rename-replace into output_dir, sweep
orphans. The legacy symlink-swap and one-shot migration paths are gone.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
import zlib
from pathlib import Path

import pytest

import kayak.web.build._shared as shared_mod
import kayak.web.build.deploy as build_mod
from kayak.dataset.map import MapConfig, MapLayer
from kayak.dataset.site import SiteConfig
from kayak.web.build.deploy import (
    _deploy_staging_to_live,
    _sweep_orphans,
)
from kayak.web.regression import UnsafeContentError, _filter_regression_md_for_html


def test_filter_regression_md_drops_sql_stub_and_future() -> None:
    md = (
        "# Title\n\n"
        "## Data\n\ntable...\n\n"
        "## Chosen fit\n\nstuff\n\n"
        "## SQL stub for `calc_expression`\n\n"
        "```sql\nINSERT INTO ...;\n```\n\n"
        "## Future\n\n- piecewise idea\n"
    )
    out = _filter_regression_md_for_html(md)
    assert "## Data" in out
    assert "## Chosen fit" in out
    assert "## SQL stub" not in out
    assert "INSERT INTO" not in out
    assert "## Future" not in out
    assert "piecewise" not in out


def test_filter_regression_md_drops_calc_expression_row_section() -> None:
    # Post-redesign reports carry "## `calc_expression` row" (the kayak_data
    # CSV column values) instead of the SQL stub — equally maintainer-only.
    md = (
        "# Title\n\n"
        "## Chosen fit\n\nstuff\n\n"
        "## `calc_expression` row\n\n"
        "```\nexpression: round(greatest(0, ...))\n```\n\n"
        "## Future\n\n- idea\n"
    )
    out = _filter_regression_md_for_html(md)
    assert "## Chosen fit" in out
    assert "calc_expression` row" not in out
    assert "expression: round" not in out


def test_filter_regression_md_chops_run_until_next_h2() -> None:
    # A non-dropped H2 following a dropped one survives.
    md = "## Drop me\n## SQL stub for X\n\nSQL goes here\n\n## Keep me\n\nthis section is fine\n"
    out = _filter_regression_md_for_html(md)
    assert "## SQL stub" not in out
    assert "SQL goes here" not in out
    assert "## Keep me" in out
    assert "this section is fine" in out


def test_filter_regression_md_drops_generated_by_block() -> None:
    md = (
        "# Linear regression: foo\n\n"
        "**Goal**: estimate ...\n\n"
        "Generated by:\n\n"
        "```bash\n"
        "python3 scripts/regression/gauge_pair_linear.py \\\n"
        "    --predictor 14330000 --target 14328000\n"
        "```\n\n"
        "## Data\n\nstuff\n"
    )
    out = _filter_regression_md_for_html(md)
    assert "**Goal**" in out
    assert "Generated by:" not in out
    assert "python3 scripts/regression" not in out
    assert "```bash" not in out
    assert "## Data" in out
    assert "stuff" in out


def test_filter_regression_md_rewrites_sibling_md_links() -> None:
    # Sibling cross-links must become .html (the published site serves .html);
    # external/absolute links and code spans are left alone.
    md = (
        "See [`foo_leadlag.md`](./foo_leadlag.md) and "
        "[the daily fit](./bar_from_baz.md).\n"
        "Not a link: `gauge_lead_lag.py`. External: [x](https://e.org/a.md).\n"
    )
    out = _filter_regression_md_for_html(md)
    assert "](./foo_leadlag.html)" in out
    assert "](./bar_from_baz.html)" in out
    assert "./foo_leadlag.md)" not in out
    assert "`gauge_lead_lag.py`" in out  # code span untouched
    assert "https://e.org/a.md" in out  # external link untouched


def _write(p: Path, content: str, mode: int = 0o644) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content)
    p.chmod(mode)


def _png_bytes(width: int, height: int, rgb: bytes = b"\x00\x00\x00") -> bytes:
    def chunk(kind: bytes, data: bytes) -> bytes:
        body = kind + data
        return (
            struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)
        )

    raw = b"".join(b"\x00" + rgb * width for _ in range(height))
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(raw))
        + chunk(b"IEND", b"")
    )


def _png_size(data: bytes) -> tuple[int, int]:
    assert data[:8] == b"\x89PNG\r\n\x1a\n"
    return struct.unpack(">II", data[16:24])


def test_deploy_to_empty_live(tmp_path: Path) -> None:
    """Happy path: empty live tree, three files in two dirs all land."""
    staging = tmp_path / "stage"
    live = tmp_path / "live"
    live.mkdir()
    _write(staging / "index.html", "<html>new</html>")
    _write(staging / "static/style.css", "body {}")
    _write(staging / "static/app.js", "console.log(1)")

    kept = _deploy_staging_to_live(staging, live)

    assert kept == {
        Path("index.html"),
        Path("static/style.css"),
        Path("static/app.js"),
    }
    assert (live / "index.html").read_text() == "<html>new</html>"
    assert (live / "static/style.css").read_text() == "body {}"
    assert (live / "static/app.js").read_text() == "console.log(1)"


def test_deploy_updates_existing(tmp_path: Path) -> None:
    """Files already in live get their content atomically replaced."""
    staging = tmp_path / "stage"
    live = tmp_path / "live"
    _write(live / "index.html", "<html>old</html>")
    _write(staging / "index.html", "<html>new</html>")

    # Inode before so we can assert atomic replacement, not in-place rewrite.
    old_inode = (live / "index.html").stat().st_ino

    kept = _deploy_staging_to_live(staging, live)

    assert kept == {Path("index.html")}
    assert (live / "index.html").read_text() == "<html>new</html>"
    assert (live / "index.html").stat().st_ino != old_inode


def test_deploy_preserves_mode(tmp_path: Path) -> None:
    """File mode on the source carries to the installed file."""
    staging = tmp_path / "stage"
    live = tmp_path / "live"
    live.mkdir()
    _write(staging / "script.sh", "#!/bin/sh\necho hi\n", mode=0o755)

    _deploy_staging_to_live(staging, live)

    assert (live / "script.sh").stat().st_mode & 0o777 == 0o755


def test_deploy_creates_nested_dirs(tmp_path: Path) -> None:
    """Deeply-nested paths in staging get their parents mkdir'd in live."""
    staging = tmp_path / "stage"
    live = tmp_path / "live"
    live.mkdir()
    _write(staging / "a/b/c/d.txt", "deep")

    kept = _deploy_staging_to_live(staging, live)

    assert kept == {Path("a/b/c/d.txt")}
    assert (live / "a/b/c/d.txt").read_text() == "deep"


def test_deploy_skips_empty_dirs(tmp_path: Path) -> None:
    """Empty directories in staging are not propagated."""
    staging = tmp_path / "stage"
    live = tmp_path / "live"
    live.mkdir()
    (staging / "empty").mkdir(parents=True)
    _write(staging / "real.txt", "content")

    kept = _deploy_staging_to_live(staging, live)

    assert kept == {Path("real.txt")}
    assert not (live / "empty").exists()


def test_deploy_leaves_no_dotnew_temp_files(tmp_path: Path) -> None:
    """The `.new` scratch files used for atomic rename should not remain."""
    staging = tmp_path / "stage"
    live = tmp_path / "live"
    live.mkdir()
    _write(staging / "a.html", "x")
    _write(staging / "nested/b.html", "y")

    _deploy_staging_to_live(staging, live)

    leftovers = [p for p in live.rglob("*.new") if p.is_file()]
    assert leftovers == []


def test_sweep_removes_orphans(tmp_path: Path) -> None:
    """Files in live not in kept get unlinked; kept files untouched."""
    live = tmp_path / "live"
    _write(live / "keep.html", "keep")
    _write(live / "drop.html", "drop")
    _write(live / "static/keep.css", "k")
    _write(live / "static/drop.css", "d")

    kept = {Path("keep.html"), Path("static/keep.css")}
    removed = _sweep_orphans(live, kept)

    assert set(removed) == {Path("drop.html"), Path("static/drop.css")}
    assert (live / "keep.html").exists()
    assert (live / "static/keep.css").exists()
    assert not (live / "drop.html").exists()
    assert not (live / "static/drop.css").exists()


def test_sweep_noop_when_kept_matches_live(tmp_path: Path) -> None:
    """When kept covers every file, nothing is removed."""
    live = tmp_path / "live"
    _write(live / "a.html", "a")
    _write(live / "b.html", "b")

    removed = _sweep_orphans(live, {Path("a.html"), Path("b.html")})

    assert removed == []
    assert (live / "a.html").exists()
    assert (live / "b.html").exists()


def test_deploy_then_sweep_full_cycle(tmp_path: Path) -> None:
    """End-to-end: a live dir with old content gets fully transitioned
    to the new build — updated files, new files, removed orphans."""
    staging = tmp_path / "stage"
    live = tmp_path / "live"

    # Previous build (in live)
    _write(live / "index.html", "<html>v1</html>")
    _write(live / "removed.html", "gone next build")
    _write(live / "static/old-asset.css", "old")

    # New build (in staging)
    _write(staging / "index.html", "<html>v2</html>")
    _write(staging / "new-page.html", "added this build")
    _write(staging / "static/new-asset.css", "new")

    kept = _deploy_staging_to_live(staging, live)
    removed = _sweep_orphans(live, kept)

    assert (live / "index.html").read_text() == "<html>v2</html>"
    assert (live / "new-page.html").read_text() == "added this build"
    assert (live / "static/new-asset.css").read_text() == "new"
    assert not (live / "removed.html").exists()
    assert not (live / "static/old-asset.css").exists()
    assert set(removed) == {Path("removed.html"), Path("static/old-asset.css")}


def test_deploy_skips_symlinks_in_staging(tmp_path: Path) -> None:
    """Symlinks in staging are not propagated — build output shouldn't
    contain them, and carrying a symlink over would be surprising."""
    staging = tmp_path / "stage"
    live = tmp_path / "live"
    live.mkdir()
    _write(staging / "real.txt", "content")
    (staging / "link.txt").symlink_to("real.txt")

    kept = _deploy_staging_to_live(staging, live)

    assert kept == {Path("real.txt")}
    assert not (live / "link.txt").exists()


def test_sweep_ignores_symlinks(tmp_path: Path) -> None:
    """A symlink in live is not treated as an orphan file — leave it alone
    so we don't accidentally delete unrelated operator-created links."""
    live = tmp_path / "live"
    _write(live / "target.txt", "t")
    (live / "link.txt").symlink_to("target.txt")

    removed = _sweep_orphans(live, {Path("target.txt")})

    assert removed == []
    assert (live / "link.txt").is_symlink()


def test_deploy_error_leaves_live_consistent(tmp_path: Path) -> None:
    """If a mid-deploy rename blows up, the files renamed so far are valid
    (inodes committed) and the remaining files are untouched in live.

    We simulate by making the live tree read-only partway through via a
    monkeypatched copy2 that raises on the second file.
    """
    staging = tmp_path / "stage"
    live = tmp_path / "live"
    live.mkdir()
    _write(live / "preserved.html", "original")
    _write(staging / "a.html", "new-a")
    _write(staging / "b.html", "new-b")

    orig_copy2 = build_mod.shutil.copy2
    calls: list[Path] = []

    def boom_on_second(src, dst, *a, **kw):
        calls.append(Path(dst))
        if len(calls) >= 2:
            raise OSError("simulated mid-deploy failure")
        return orig_copy2(src, dst, *a, **kw)

    with pytest.MonkeyPatch.context() as mp:
        mp.setattr(build_mod.shutil, "copy2", boom_on_second)
        with pytest.raises(OSError, match="simulated mid-deploy failure"):
            _deploy_staging_to_live(staging, live)

    # Whichever file got through first is a valid file; the other is absent
    # or still a .new temp that we explicitly check isn't visible as final.
    finals = sorted(p.name for p in live.iterdir() if p.is_file())
    # preserved.html is always there; at most one of a.html/b.html made it.
    assert "preserved.html" in finals
    assert (live / "preserved.html").read_text() == "original"


# ---------------------------------------------------------------------------
# build() wire-up: single rename-over-target deploy path
# ---------------------------------------------------------------------------


def _stub_build_to_dir_factory(files: dict[str, str]):
    """Factory for a `_build_to_dir` stub that writes a known file set."""

    def _stub(out_dir: Path, _args: argparse.Namespace) -> None:
        for rel, content in files.items():
            p = out_dir / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content)

    return _stub


def test_build_requires_explicit_output_dir(monkeypatch: pytest.MonkeyPatch) -> None:
    """No --output-dir and no $OUTPUT_DIR → hard error with guidance (S3h):
    the old in-repo public_html/ default is gone; build writes only a
    caller-supplied directory."""
    monkeypatch.delenv("OUTPUT_DIR", raising=False)
    with pytest.raises(SystemExit):
        build_mod.build(argparse.Namespace(output_dir=None))


@pytest.mark.parametrize("sub", ["", "public_html", "src/kayak/web"])
def test_build_refuses_engine_checkout_output(sub: str) -> None:
    """The engine source tree (root or any subdir) is refused as output."""
    target = build_mod.BASE_DIR / sub if sub else build_mod.BASE_DIR
    with pytest.raises(SystemExit):
        build_mod.build(argparse.Namespace(output_dir=str(target)))


def test_build_refuses_dataset_dir_output(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """DATASET_DIR (and anything below it) is refused as output — generated
    HTML must never mix into the reviewed dataset checkout."""
    monkeypatch.setattr(build_mod, "DATASET_DIR", tmp_path)
    with pytest.raises(SystemExit):
        build_mod.build(argparse.Namespace(output_dir=str(tmp_path / "regression")))


def test_build_stages_then_renames(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """build() stages, rename-deploys, sweeps orphans, cleans the staging dir."""
    live = tmp_path / "public_html"
    live.mkdir()
    (live / "orphan.html").write_text("will be swept")
    (live / "index.html").write_text("v0")
    old_index_inode = (live / "index.html").stat().st_ino

    monkeypatch.setattr(
        build_mod,
        "_build_to_dir",
        _stub_build_to_dir_factory(
            {
                "index.html": "v1",
                "static/app.js": "console.log(1)",
            }
        ),
    )
    monkeypatch.setattr(build_mod, "_set_acls", lambda _p: None)

    build_mod.build(argparse.Namespace(output_dir=str(live)))

    assert (live / "index.html").read_text() == "v1"
    assert (live / "index.html").stat().st_ino != old_index_inode
    assert (live / "static/app.js").read_text() == "console.log(1)"
    assert not (live / "orphan.html").exists()
    assert not (tmp_path / "public_html.staging").exists()


def test_build_creates_output_dir_if_missing(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A missing output_dir is created — first-build-on-fresh-host path."""
    live = tmp_path / "public_html"
    # Note: live does not exist yet.
    monkeypatch.setattr(
        build_mod,
        "_build_to_dir",
        _stub_build_to_dir_factory({"index.html": "v1"}),
    )
    monkeypatch.setattr(build_mod, "_set_acls", lambda _p: None)

    build_mod.build(argparse.Namespace(output_dir=str(live)))

    assert live.is_dir()
    assert (live / "index.html").read_text() == "v1"


def test_build_to_dir_refuses_publishable_dataset_without_site_url(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    (tmp_path / "dataset.yaml").write_text(
        "contract_version: 1\n"
        "dataset_id: test\n"
        "name: Test Levels\n"
        "status: publishable\n"
        "license: CC-BY-NC-4.0\n"
        'engine_test_ref: "0000000000000000000000000000000000000000"\n',
        encoding="utf-8",
    )
    monkeypatch.setattr(build_mod, "DATASET_DIR", tmp_path)
    monkeypatch.delenv("SITE_URL", raising=False)
    monkeypatch.setattr(
        build_mod,
        "get_session",
        lambda: pytest.fail("build should fail before opening the DB"),
    )

    with pytest.raises(RuntimeError, match="SITE_URL must be set explicitly"):
        build_mod._build_to_dir(tmp_path / "out", argparse.Namespace())


def test_build_reports_publishable_site_url_error_cleanly(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    # Dataset and output are SIBLINGS: the S3h output guard refuses an output
    # dir inside DATASET_DIR before the site-URL check this test targets runs.
    dataset = tmp_path / "dataset"
    dataset.mkdir()
    (dataset / "dataset.yaml").write_text(
        "contract_version: 1\n"
        "dataset_id: test\n"
        "name: Test Levels\n"
        "status: publishable\n"
        "license: CC-BY-NC-4.0\n"
        'engine_test_ref: "0000000000000000000000000000000000000000"\n',
        encoding="utf-8",
    )
    live = tmp_path / "public_html"
    monkeypatch.setattr(build_mod, "DATASET_DIR", dataset)
    monkeypatch.delenv("SITE_URL", raising=False)
    monkeypatch.setattr(
        build_mod,
        "get_session",
        lambda: pytest.fail("build should fail before opening the DB"),
    )

    with pytest.raises(SystemExit) as exc:
        build_mod.build(argparse.Namespace(output_dir=str(live)))
    assert exc.value.code == 1
    assert "SITE_URL must be set explicitly" in capsys.readouterr().err
    assert not (live / ".staging").exists()


def test_build_cleans_staging_on_failure(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """If _build_to_dir raises mid-build, the staging dir is torn down so a
    retry doesn't trip over stale scratch state. Live is untouched."""
    live = tmp_path / "public_html"
    live.mkdir()
    (live / "index.html").write_text("untouched")

    def _exploding_build_to_dir(out_dir: Path, _args: argparse.Namespace) -> None:
        (out_dir / "half.html").write_text("partial")
        raise RuntimeError("boom mid-build")

    monkeypatch.setattr(build_mod, "_build_to_dir", _exploding_build_to_dir)
    monkeypatch.setattr(build_mod, "_set_acls", lambda _p: None)

    with pytest.raises(RuntimeError, match="boom mid-build"):
        build_mod.build(argparse.Namespace(output_dir=str(live)))

    assert (live / "index.html").read_text() == "untouched"
    # Staging dir lives at <live>/.staging post-QW.6; finally cleared it.
    assert not (live / ".staging").exists()


def test_build_removes_stale_staging_before_rebuild(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A stale .staging dir from a previous aborted run is wiped before
    the new build writes to it.

    Post-QW.6 staging lives at ``<output_dir>/.staging``, not as a sibling,
    so the QW.6 systemd ReadWritePaths bind-mount finds it inside the
    always-present output_dir.
    """
    live = tmp_path / "public_html"
    live.mkdir()
    stale_staging = live / ".staging"
    stale_staging.mkdir()
    (stale_staging / "leftover.html").write_text("from a prior aborted build")

    monkeypatch.setattr(
        build_mod,
        "_build_to_dir",
        _stub_build_to_dir_factory({"index.html": "fresh"}),
    )
    monkeypatch.setattr(build_mod, "_set_acls", lambda _p: None)

    build_mod.build(argparse.Namespace(output_dir=str(live)))

    assert (live / "index.html").read_text() == "fresh"
    assert not (live / "leftover.html").exists()
    assert not stale_staging.exists()


# --------------------------------------------------------------------------- #
# _deploy_regression_artifacts: render + sanitize (fail-closed) the published set.
# --------------------------------------------------------------------------- #


def _seed_regression(base: Path, *, svg: str | None = None) -> None:
    """Stage a regression/ under a fake DATASET_DIR with one clean report."""
    reg = base / "regression"
    reg.mkdir(parents=True)
    (reg / "r.md").write_text(
        "# R\n\n![plot](./r.svg)\n\nGenerated by:\n\n```bash\nx\n```\n\n## Fit\n\nok\n"
    )
    (reg / "r.svg").write_text(
        svg or '<svg xmlns="http://www.w3.org/2000/svg"><rect x="1" y="2" fill="#fff"/></svg>'
    )
    (reg / "r.json").write_text('{"slug":"r","r2":0.9}')


def test_deploy_regression_renders_and_sanitizes(tmp_path, monkeypatch):
    monkeypatch.setattr(build_mod, "DATASET_DIR", tmp_path)
    _seed_regression(tmp_path)
    static_dir = tmp_path / "out" / "static"
    static_dir.mkdir(parents=True)
    build_mod._deploy_regression_artifacts(static_dir)

    out = static_dir / "regression"
    html = (out / "r.html").read_text()
    assert "## Fit".lower() not in html.lower() and "Fit" in html  # rendered, not raw
    assert "Generated by" not in html  # maintainer preamble dropped
    svg_out = (out / "r.svg").read_text()
    assert svg_out.startswith('<svg xmlns="http://www.w3.org/2000/svg"')  # re-serialized
    assert (out / "r.json").is_file()


def test_deploy_regression_rejects_malicious_svg(tmp_path, monkeypatch):
    monkeypatch.setattr(build_mod, "DATASET_DIR", tmp_path)
    _seed_regression(
        tmp_path, svg='<svg xmlns="http://www.w3.org/2000/svg"><script>x</script></svg>'
    )
    static_dir = tmp_path / "out" / "static"
    static_dir.mkdir(parents=True)
    with pytest.raises(UnsafeContentError):
        build_mod._deploy_regression_artifacts(static_dir)


def test_deploy_regression_missing_dir_is_noop(tmp_path, monkeypatch):
    monkeypatch.setattr(build_mod, "DATASET_DIR", tmp_path)  # no regression/ under it
    static_dir = tmp_path / "out" / "static"
    static_dir.mkdir(parents=True)
    build_mod._deploy_regression_artifacts(static_dir)  # must not raise
    assert not (static_dir / "regression").exists()


def test_deploy_regression_warns_when_slugs_but_no_dir(tmp_path, monkeypatch, caplog):
    # Reports are expected (the DB declares provenance_slugs) but DATASET_DIR/regression/
    # is absent — a stale/misconfigured checkout. Build must not fail, but must warn so
    # the silently-dropped pages surface (parallel to validate-dataset's deploy check).
    monkeypatch.setattr(build_mod, "DATASET_DIR", tmp_path)  # no regression/ under it
    static_dir = tmp_path / "out" / "static"
    static_dir.mkdir(parents=True)
    with caplog.at_level("WARNING"):
        build_mod._deploy_regression_artifacts(static_dir, provenance_slug_count=3)
    assert not (static_dir / "regression").exists()  # no crash, no output
    assert "3 calc_expression provenance_slug" in caplog.text
    assert "no regression reports will be published" in caplog.text


def test_count_regression_slugs(session):
    # The count that drives the stale-checkout warning: non-empty provenance_slugs
    # only. NULL and whitespace-only slugs don't count (they declare no report).
    from kayak.db.models import CalcExpression, DataType

    assert build_mod._count_regression_slugs(session) == 0
    session.add_all(
        [
            CalcExpression(data_type=DataType.flow, expression="a", provenance_slug="rogue_at_x"),
            CalcExpression(data_type=DataType.flow, expression="b", provenance_slug="smith_at_y"),
            CalcExpression(data_type=DataType.flow, expression="c", provenance_slug=None),
            CalcExpression(data_type=DataType.flow, expression="d", provenance_slug="   "),
        ]
    )
    session.flush()
    assert build_mod._count_regression_slugs(session) == 2


def test_deploy_source_files_threads_slug_count_to_warning(tmp_path, monkeypatch, caplog):
    # End-to-end threading: _deploy_source_files → _deploy_static_assets →
    # _deploy_regression_artifacts must carry provenance_slug_count through all three
    # hops, so the warning fires when the count is set but DATASET_DIR/regression/ is
    # absent. Closes the gap between the leaf-level warn test and _build_to_dir.
    monkeypatch.setattr(build_mod, "DATASET_DIR", tmp_path)  # no regression/ under it
    monkeypatch.setattr(build_mod, "MAP_LAYERS_DIR", tmp_path / "no-map-layers")
    output_dir = tmp_path / "out"
    with caplog.at_level("WARNING"):
        build_mod._deploy_source_files(output_dir, provenance_slug_count=7)
    assert "7 calc_expression provenance_slug" in caplog.text


def test_deploy_regression_skips_unsafe_stem(tmp_path, monkeypatch):
    # A file whose NAME isn't a safe slug (HTML metacharacters) must never be
    # processed/published — closes the orphan-filename <title> injection path.
    monkeypatch.setattr(build_mod, "DATASET_DIR", tmp_path)
    _seed_regression(tmp_path)  # the clean r.{md,svg,json}
    reg = tmp_path / "regression"
    (reg / "bad<x>.svg").write_text('<svg xmlns="http://www.w3.org/2000/svg"><rect/></svg>')
    (reg / "bad<x>.json").write_text('{"slug":"x"}')
    (reg / "bad<x>.md").write_text("# evil\n")
    static_dir = tmp_path / "out" / "static"
    static_dir.mkdir(parents=True)
    build_mod._deploy_regression_artifacts(static_dir)

    out = static_dir / "regression"
    assert (out / "r.html").is_file()  # safe-stem report still published
    assert not (out / "bad<x>.svg").exists()
    assert not (out / "bad<x>.json").exists()
    assert not (out / "bad<x>.html").exists()


# --------------------------------------------------------------------------- #
# Brand color templating (S3a-3): CSS :root + manifest theme_color
# --------------------------------------------------------------------------- #


def test_apply_brand_color_default_is_noop():
    # With the default brand, _apply_brand_color returns the text unchanged.
    text = "a #1b5591 b"
    assert shared_mod._apply_brand_color(text) == text


def test_apply_brand_color_custom_substitutes(monkeypatch):
    monkeypatch.setattr(shared_mod, "BRAND_COLOR", "#abcdef")
    assert shared_mod._apply_brand_color("x #1b5591 y #1b5591") == "x #abcdef y #abcdef"


def test_load_css_applies_custom_brand(monkeypatch):
    # The built CSS recolors the :root brand vars; the default #1b5591 (which
    # appears only at --c-primary/--c-link) is gone, the dark-mode link is untouched.
    monkeypatch.setattr(shared_mod, "BRAND_COLOR", "#abcdef")
    css = shared_mod._load_css()
    assert "#abcdef" in css
    assert "#1b5591" not in css
    assert "#6ab0f3" in css  # dark-mode --c-link, a separate color, preserved


def _deploy_static_no_externals(monkeypatch, tmp_path, site_config: SiteConfig | None = None):
    """Run _deploy_static_assets with map-layer + regression dirs absent."""
    output = _deploy_static_no_externals_output(monkeypatch, tmp_path, site_config)
    return (output / "static" / "manifest.json").read_text(encoding="utf-8")


def _deploy_static_no_externals_output(
    monkeypatch, tmp_path, site_config: SiteConfig | None = None
):
    """Run _deploy_static_assets with map-layer + regression dirs absent."""
    monkeypatch.setattr(build_mod, "MAP_LAYERS_DIR", tmp_path / "no-map-layers")
    monkeypatch.setattr(build_mod, "DATASET_DIR", tmp_path / "no-ds")
    monkeypatch.setattr(build_mod, "get_site_config", lambda: site_config or SiteConfig())
    output = tmp_path / "out"
    build_mod._deploy_static_assets(output)
    return output


def test_deploy_manifest_default_identity_and_brand(monkeypatch, tmp_path):
    manifest = _deploy_static_no_externals(monkeypatch, tmp_path)
    data = json.loads(manifest)
    assert data["name"] == "River Levels"
    assert data["short_name"] == "Levels"
    assert data["theme_color"] == "#1b5591"


def test_deploy_manifest_custom_brand(monkeypatch, tmp_path):
    monkeypatch.setattr(shared_mod, "BRAND_COLOR", "#abcdef")
    manifest = _deploy_static_no_externals(monkeypatch, tmp_path)
    assert '"theme_color": "#abcdef"' in manifest
    assert "#1b5591" not in manifest


def test_deploy_manifest_custom_site_identity(monkeypatch, tmp_path):
    manifest = _deploy_static_no_externals(
        monkeypatch,
        tmp_path,
        SiteConfig(
            site_name="Example River Levels",
            manifest_name="Example Levels",
            manifest_short_name="Example",
        ),
    )
    data = json.loads(manifest)
    assert data["name"] == "Example Levels"
    assert data["short_name"] == "Example"


def test_deploy_security_txt_default_is_packaged_noop(monkeypatch, tmp_path):
    output = _deploy_static_no_externals_output(monkeypatch, tmp_path)
    security_txt = (output / "static" / "security.txt").read_text(encoding="utf-8")
    packaged = (build_mod._STATIC_DIR / "security.txt").read_text(encoding="utf-8")
    assert security_txt == packaged
    assert "pat.kayak@gmail.com" not in security_txt


def test_deploy_security_txt_custom_site_fields(monkeypatch, tmp_path):
    output = _deploy_static_no_externals_output(
        monkeypatch,
        tmp_path,
        SiteConfig(
            security_contact="mailto:security@example.org",
            security_expires="2027-12-31T00:00:00Z",
        ),
    )
    security_txt = (output / "static" / "security.txt").read_text(encoding="utf-8")
    assert "Contact: mailto:security@example.org\n" in security_txt
    assert "Expires: 2027-12-31T00:00:00Z\n" in security_txt
    assert "Preferred-Languages: en\n" in security_txt


def test_deploy_static_assets_prefers_dataset_site_assets(monkeypatch, tmp_path):
    ds = tmp_path / "ds"
    asset_dir = ds / "site" / "assets"
    asset_dir.mkdir(parents=True)
    override = _png_bytes(1200, 630, b"\x10\x20\x30")
    (asset_dir / "og-image.png").write_bytes(override)

    output = tmp_path / "out"
    monkeypatch.setattr(build_mod, "MAP_LAYERS_DIR", tmp_path / "no-map-layers")
    monkeypatch.setattr(build_mod, "DATASET_DIR", ds)
    monkeypatch.setattr(build_mod, "get_site_config", lambda: SiteConfig())
    build_mod._deploy_static_assets(output)

    assert (output / "static" / "og-image.png").read_bytes() == override


def test_deploy_static_assets_rejects_invalid_dataset_site_assets(monkeypatch, tmp_path):
    ds = tmp_path / "ds"
    asset_dir = ds / "site" / "assets"
    asset_dir.mkdir(parents=True)
    (asset_dir / "og-image.png").write_bytes(_png_bytes(1200, 600))

    output = tmp_path / "out"
    monkeypatch.setattr(build_mod, "MAP_LAYERS_DIR", tmp_path / "no-map-layers")
    monkeypatch.setattr(build_mod, "DATASET_DIR", ds)
    monkeypatch.setattr(build_mod, "get_site_config", lambda: SiteConfig())

    with pytest.raises(RuntimeError, match="invalid dataset site/assets"):
        build_mod._deploy_static_assets(output)


def _one_overlay_map_config() -> MapConfig:
    """A map config with a single overlay layer staged as ``osmb-test.geojson``."""
    layer = MapLayer(
        key="testlayer",
        label="Test Layer",
        color="#123456",
        shape="circle",
        size=5,
        popup="access",
        popup_link="https://example.com/info",
        output_filename="osmb-test.geojson",
        endpoint="https://example.com/arcgis/FeatureServer/0",
    )
    return MapConfig(
        center=[44.0, -120.5], zoom=7, bbox=[-124.7, 41.9, -116.4, 46.3], layers=[layer]
    )


def test_deploy_static_copies_staged_overlay_and_emits_url(monkeypatch, tmp_path):
    # Consumer-half regression guard for the MAP_LAYERS_DIR split (PR #204):
    # host_render wires the env onto the pipeline; THIS asserts what build does with
    # it — when the staging dir holds a configured overlay GeoJSON, build copies it
    # into static/ and _map_layer_url emits a non-empty cache-busted URL (so map.js
    # renders the layer's checkbox).
    monkeypatch.setattr(build_mod, "get_map_config", _one_overlay_map_config)
    staging = tmp_path / "map-layers"
    staging.mkdir()
    (staging / "osmb-test.geojson").write_text('{"type":"FeatureCollection","features":[]}')
    monkeypatch.setattr(build_mod, "MAP_LAYERS_DIR", staging)
    monkeypatch.setattr(build_mod, "DATASET_DIR", tmp_path / "no-ds")
    monkeypatch.setattr(build_mod, "get_site_config", lambda: SiteConfig())

    output = tmp_path / "out"
    build_mod._deploy_static_assets(output)

    static_dir = output / "static"
    assert (static_dir / "osmb-test.geojson").is_file()
    assert build_mod._map_layer_url(static_dir, "osmb-test.geojson").startswith(
        "/static/osmb-test.geojson?v="
    )


def test_deploy_static_skips_unstaged_overlay_and_url_is_empty(monkeypatch, tmp_path):
    # The flip side and the actual failure mode: a configured layer whose GeoJSON is
    # NOT in the staging dir (the nightly fetch hasn't landed it, or — the bug —
    # MAP_LAYERS_DIR resolved to the wrong/empty dir) is not copied, and
    # _map_layer_url returns "" → map.js renders no checkbox.
    monkeypatch.setattr(build_mod, "get_map_config", _one_overlay_map_config)
    staging = tmp_path / "empty-map-layers"
    staging.mkdir()  # present but missing the overlay file
    monkeypatch.setattr(build_mod, "MAP_LAYERS_DIR", staging)
    monkeypatch.setattr(build_mod, "DATASET_DIR", tmp_path / "no-ds")
    monkeypatch.setattr(build_mod, "get_site_config", lambda: SiteConfig())

    output = tmp_path / "out"
    build_mod._deploy_static_assets(output)

    static_dir = output / "static"
    assert not (static_dir / "osmb-test.geojson").exists()
    assert build_mod._map_layer_url(static_dir, "osmb-test.geojson") == ""


def test_packaged_og_image_fallback_is_generic():
    data = (build_mod._STATIC_DIR / "og-image.png").read_bytes()
    old_wkcc_sha256 = "bd455472ece6dfded63de4e08d4c0a34c42ec6b6424998d2d81c3c42ee010a39"

    assert hashlib.sha256(data).hexdigest() != old_wkcc_sha256
    assert _png_size(data) == (1200, 630)


def test_apply_brand_color_case_insensitive_noop(monkeypatch):
    # Same color in a different case is a no-op (no pointless CSS-hash churn).
    monkeypatch.setattr(shared_mod, "BRAND_COLOR", "#1B5591")
    text = "a #1b5591 b"
    assert shared_mod._apply_brand_color(text) == text


def test_deploy_php_root_style_css_default_brand(tmp_path):
    # The root /style.css (PHP no-hash fallback + regression-page stylesheet) keeps
    # the default brand when no site.yaml is set.
    output = tmp_path / "out"
    output.mkdir()
    build_mod._deploy_php_files(output)
    css = (output / "style.css").read_text(encoding="utf-8")
    assert "--c-primary: #1b5591;" in css


def test_deploy_php_root_style_css_custom_brand(monkeypatch, tmp_path):
    # A custom brand must reach the root /style.css too (the #158 review Medium —
    # it was copied verbatim, leaving fallback/regression pages engine-blue).
    monkeypatch.setattr(shared_mod, "BRAND_COLOR", "#abcdef")
    output = tmp_path / "out"
    output.mkdir()
    build_mod._deploy_php_files(output)
    css = (output / "style.css").read_text(encoding="utf-8")
    assert "--c-primary: #abcdef;" in css
    assert "#1b5591" not in css


# --------------------------------------------------------------------------- #
# Site prose fragments (S3c): DATASET_DIR/site/<page>.md → OUTPUT_DIR/prose/<page>.html
# --------------------------------------------------------------------------- #


def test_deploy_site_prose_renders_fragments(monkeypatch, tmp_path):
    ds = tmp_path / "ds"
    (ds / "site").mkdir(parents=True)
    (ds / "site" / "about.md").write_text("## About\n\nWe are **Foo**. <script>x</script>\n")
    monkeypatch.setattr(build_mod, "DATASET_DIR", ds)
    output = tmp_path / "out"
    output.mkdir()
    build_mod._deploy_site_prose(output)
    frag = (output / "prose" / "about.html").read_text(encoding="utf-8")
    assert "<h2>About</h2>" in frag and "<strong>Foo</strong>" in frag
    assert "<script" not in frag  # sanitized
    # A page with no .md gets no fragment (PHP falls back).
    assert not (output / "prose" / "privacy.html").exists()


def test_deploy_site_prose_no_dir_is_noop(monkeypatch, tmp_path):
    monkeypatch.setattr(build_mod, "DATASET_DIR", tmp_path / "no-ds")
    output = tmp_path / "out"
    output.mkdir()
    build_mod._deploy_site_prose(output)  # must not raise
    assert not (output / "prose").exists()


def test_deploy_site_prose_rejects_symlinked_site_dir(monkeypatch, tmp_path):
    ds = tmp_path / "ds"
    outside = tmp_path / "outside-site"
    outside.mkdir()
    ds.mkdir()
    (ds / "site").symlink_to(outside)
    monkeypatch.setattr(build_mod, "DATASET_DIR", ds)

    output = tmp_path / "out"
    output.mkdir()
    with pytest.raises(RuntimeError, match="site symlinks are not supported"):
        build_mod._deploy_site_prose(output)


def test_deploy_site_prose_rejects_symlinked_page(monkeypatch, tmp_path):
    ds = tmp_path / "ds"
    (ds / "site").mkdir(parents=True)
    target = tmp_path / "privacy.md"
    target.write_text("# Outside\n\nNot dataset-owned.\n", encoding="utf-8")
    (ds / "site" / "privacy.md").symlink_to(target)
    monkeypatch.setattr(build_mod, "DATASET_DIR", ds)

    output = tmp_path / "out"
    output.mkdir()
    with pytest.raises(RuntimeError, match=r"site/privacy\.md symlinks are not supported"):
        build_mod._deploy_site_prose(output)


# --------------------------------------------------------------------------- #
# site-config.json generation (S3d)
# --------------------------------------------------------------------------- #


def test_build_site_config_engine_defaults(monkeypatch, tmp_path) -> None:
    import json

    from kayak.dataset import map as dataset_map
    from kayak.web.build.site_config import build_site_config

    monkeypatch.setattr("kayak.config.DATASET_DIR", tmp_path)
    dataset_map.get_map_config.cache_clear()

    # No dataset map.yaml means the engine contributes no regional overlay layers.
    def map_layer_url(fn: str) -> str:
        raise AssertionError(f"no default overlay filename should be resolved: {fn}")

    try:
        cfg = json.loads(build_site_config(map_layer_url))
    finally:
        dataset_map.get_map_config.cache_clear()

    assert cfg["map"] == {"center": [0.0, 0.0], "zoom": 2}
    assert cfg["layers"] == []


def test_build_site_config_is_stable(monkeypatch, tmp_path) -> None:
    # sort_keys makes the output reproducible across builds (byte-identity anchor
    # for the generated site-config artifact).
    from kayak.dataset import map as dataset_map
    from kayak.web.build.site_config import build_site_config

    monkeypatch.setattr("kayak.config.DATASET_DIR", tmp_path)
    dataset_map.get_map_config.cache_clear()
    try:
        a = build_site_config(lambda fn: "")
        b = build_site_config(lambda fn: "")
    finally:
        dataset_map.get_map_config.cache_clear()

    assert a == b
    assert a.endswith("\n")
