#! /bin/bash
#
# Replace the description table in mysql
#
# Pipe into mysql to actually do it

DB=levels_information
TABLE=Builder
MAPTABLE=MapBuilder

mkTable() {
  table=$1

  cat <<EOI
    drop table if exists $table;

    create table $table 
      (sortKey int key comment 'How to sort the rows',
       qUse text not null comment 'Where to use (h=html,c=csv,t=text,f=fetch)',
       type text not null comment 'How to process this field',
       field text not null comment 'Column name in master table and my internal table',
       length int not null comment 'How many columns to use in text representation',
       nameText text not null comment 'Column heading for text/csv output',
       nameHTML text not null comment 'Column heading for html output'
       )
      comment 'Information used to construct a build page';
EOI
}

mkBuilder() {
  table=$TABLE
  insert="replace into $table values"

  mkTable $table

  cat << EOI
    $insert (   0, 'f', 'noop',	'hashValue',	0, 	'', 	'');
    $insert (   1, 'f', 'noop',	'db_name',	0, 	'', 	'');
    $insert (   2, 'f', 'noop',	'state',	0, 	'', 	'');
    $insert (   3, 'f', 'noop',	'calc_expr',	0, 	'', 	'');
    $insert (   4, 'f', 'noop',	'low_flow',	0, 	'', 	'');
    $insert (   5, 'f', 'noop',	'high_flow',	0, 	'', 	'');
    $insert (   6, 'f', 'noop',	'class_flow',	0, 	'', 	'');
    $insert ( 100, 'hct','status',	'status',	4,	'Status', 'Status');
    $insert ( 200, 'fhct','name',	'display_name',	20,	'Name',	'Name');
    $insert ( 300, 'fhct','text',	'gauge_location', 10,	'Location','Location');
    $insert ( 400, 'hct','date',	'time',		14,	'Date',	'Date');
    $insert ( 500, 'hct','flow',	'flow',		7,	'Flow',	'<a href="#Units">Flow<br />CFS</a>');
    $insert ( 600, 'hct','gage',	'gage',		7,	'Height','<a href="#Units">Height<br />Feet</a>');
    $insert ( 700, 'hct','temp',	'temperature',	4,	'Temp',	'<a href="#Units">Temp<br />F</a>');
    $insert ( 800, 'fhct','text',	'drainage',	10,	'Drainage','Drainage');
    $insert ( 900, 'fhct','text',	'class',	7,	'Class','Class');

    select * from $table;
EOI
}

mkMapBuilder() {
  table=$MAPTABLE
  insert="replace into $table values"

  mkTable $table

  cat << EOI
    $insert (   0, 'f', 'noop',	'map_name',	0, 	'', 	'');
    $insert (   1, 'f', 'noop',	'db_name',	0, 	'', 	'');
    $insert (   2, 'f', 'noop',	'state',	0, 	'', 	'');
    $insert (   4, 'f', 'noop',	'low_flow',	0, 	'', 	'');
    $insert (   5, 'f', 'noop',	'high_flow',	0, 	'', 	'');

    select * from $table;
EOI
}

cat << EOI
  create database if not exists $DB;
  use $DB;
EOI

mkBuilder
mkMapBuilder
