#! /bin/bash
#
# Replace the description table in mysql
#
# Pipe into mysql to actually do it

DB=levels_information
TABLE=Edit

insert="insert into $TABLE values "

cat <<EOI
use $DB;

drop table if exists $TABLE;

create table $TABLE 
  (sortKey int key comment 'How to sort the rows',
   type text not null comment 'How to process this field',
   field text not null comment 'Column name in master table and my internal table',
   width int comment 'edit field width',
   height int comment 'edit field height',
   description text comment 'Column description',
   footnote text comment 'Supplemental information on the column'
  )
  comment 'Information used to construct a build page';

$insert (   0, 'noop',	'hashValue', 0, 0, null, null);
$insert (   1, 'notes', '', 0, 0, '<input type="submit" value="Update" name=update"><input type="submit" value="New Run" name=update">', null);
$insert (   2, 'edit',	'no_show', 1, 1, "No Show", "Do not display this entry.");
$insert (   5, 'edit',	'river_name', 50, 1, "River Name", "The river name is used for internal purposes, but should be the name of the river you are entring data for. It normally does not include which fork of the river this is, rather the main river name.");
$insert (  10, 'edit',	'display_name', 50, 1, "Name displayed", "This what is actually displayed on the web pages.");
$insert (  20, 'edit',	'Gauge_Location', 50, 1, "Gauge Location", null);
$insert (  30, 'noop',	'Class', 50, 1, null, null);
$insert (  31, 'edit',	'Class_Flow', 50, 1, "Class (I-VI)",  "This is the international rating scale. For details, please see the AWA Rating Scale information. If the class is flow dependent, you can enter this by specifying fields like: {III-IV 350 500} {IV-V 500} which says the run is a III-IV if the flow is between 350 and 500, and IV-V if it is over 500. Please note, the curly braces are very important! You can also use gauge heights, for example: {III-IV 1' 2'} {IV-V 2'} says the run is a III-IV if the gauge is between 1 and 2 feet, and a IV-V if the gauge is over 2 feet.");
$insert (  40, 'edit',	'High_Flow', 50, 1, "High flow(CFS)", "What is a high levl for this run. To specify the high value in CFS, just enter the number, 350. To specify the high value in feet, enter the number followed by a single quote, 4.5'. Please be conservative for this value. Consider what the average boater on that run would consider high! Also be aware of the differences between rafts and hard shells.");
$insert (  41, 'edit',	'Optimal_Flow', 50, 1, "Optimal flow(CFS)", "What is a good levl for this run. To specify the high value in CFS, just enter the number, 350. To specify the high value in feet, enter the number followed by a single quote, 4.5'. Be aware of the differences between rafts and hard shells.");
$insert (  42, 'edit',	'Low_Flow', 50, 1, "Low flow(CFS)", "What is the minimal water level required to run this section? To specify the low value in CFS, just enter the number, 350. To specify the low value in feet, enter the number followed by a single quote, 4.5'. Please be conservative for this value. Consider what the average boater on that run would consider low! Also be aware of the differences between rafts and hard shells.");
$insert (  50, 'edit',	'Nature', 50, 1, "Character", "This describes the feel of the run. Samples include: Big gentle river, Big desert river, ledge drops Rock gardens, narrow canyon, Pool Drop.");
$insert (  70, 'edit',	'Difficulties', 50, 1, "Difficulties", null);
$insert (  80, 'edit',	'Elevation_lost', 50, 1, "Elevation lost in feet", "difference between put in and take out in feet");
$insert (  90, 'edit',	'Drainage', 50, 1, "Drainage basin", "this section is in");
$insert ( 100, 'edit',	'Gradient', 50, 1, "Gradient feet/mile", null);
$insert ( 110, 'edit',	'Guide_Book', 50, 1, "Guide book", "for multiple guide books, use a comma seperated list");
$insert ( 120, 'edit',	'RunNumber', 50, 1, "Run # in guide book", "for multiple guide books, use a comma seperated list, in the same order as the Guide Book field");
$insert ( 130, 'edit',	'PageNumber', 50, 1, "Page # in guide book", "for multiple guide books, use a comma seperated list, in the same order as the Guide Book field");
$insert ( 140, 'edit',	'Length', 50, 1, "Run length in miles", null);
$insert ( 150, 'edit',	'State', 50, 1, "State(s) run is located in", "If a run is in two states, then can be both be listed. For example, many of the snake runs are in Oregon and Idaho, so the entry there would be Oregon Idaho For states with a space in the name, substitute an underscore for the space. For example, New Mexico becomes New_Mexico");
$insert ( 160, 'edit',	'Region', 50, 1, "Region of the state a run is in", "Which region of the state is this run in. Examples might include: Eastern, Southwestern.");
$insert ( 170, 'edit',	'Remoteness', 50, 1, "How remote is this section", null);
$insert ( 180, 'edit',	'Scenery', 50, 1, "Type of scenery on this section", null);
$insert ( 190, 'edit',	'Scenery', 50, 1, "Type of scenery on this section", null);
$insert ( 200, 'edit',	'Section', 50, 1, "Name of this section", null);
$insert ( 210, 'edit',	'Sort_Key', 50, 1, "Sort Key", "The sort key can be used to move a run updown/down in the displayed list, please be very careful with this. Let's say you have a run you want to move down in a list, you could then append an a to the sort key. Moving up is harder, though it can be done by shortening the sort key.");
$insert ( 220, 'edit',	'Description', 50, 10, "Description", null);
$insert ( 230, 'edit',	'Notes', 50, 10, "Supplemental notes", null);
$insert ( 500, 'notes', '', 0, 0, '<b>The following fields</b> are so that I can contact you if I have any questions. The e-mail address will also be used to send you a hyper link for you to approve the information you entered with in 24 hours', null);
$insert ( 510, 'edit',	'userName', 50, 1, "Your name", null);
$insert ( 520, 'edit',	'email', 50, 1, "Your e-mail address", null);

$insert ( 999, 'notes', '', 0, 0, '<input type="submit" value="Update" name=update"><input type="submit" value="New Run" name=update">', null);
$insert (1000, 'notes', '', 0, 0, "<hr></hr><b>Editing an existing run</b>", "Go to a run that you want to edit, then change all the information you feel needs changed. Then press the 'Update this entry' button. Your information will then be added into my database, and the next time my software runs, the run will be added.<h2>Please note, it might be several hours before my software runs again.</h2>");
$insert (1010, 'notes', '', 0, 0, "<hr></hr><b>Creating new runs</b>", "To create a new run, go to a run that will use the same gauge. Then edit it, being sure to change all the relevant information. Then press the 'This is a new run' button. Your information will then be added into my database, and the next time my software runs, the run will be added.<h2>Please note, it might be several hours before my software runs again.</h2>");

select * from $TABLE;
EOI
