#! /bin/bash
#
# Generate SQL records for taking my flat files to into SQL
#
# Uses the mkFlows program
#

MYPATH=`dirname $0`
SRCDIR=$MYPATH/../src

make -C $SRCDIR mkFlows

exec $SRCDIR/mkFlows $MYPATH/../databases/*
