#! /usr/bin/tclsh
#
# Translate the TCL database into SQL
#
# Feed the output of this into "mysql -u root"
#
set dbDir /home/tpw/kayaking/db.master/

set files {CBTT.gages NWSLI.gages USGS.gages 
           Arizona California Colorado Idaho Montana Nevada 
	   Oregon.Resv Soggy.array Utah Washington 
	   corrections}

proc hashValue {key} {
  global keyToHash

  if {![info exists keyToHash($key)]} {
    global hashUsed
    global hashSymbols
    global hashLength

    if {![info exists hashSymbols]} {
      set hashSymbols {0 1 2 3 4 5 6 7 8 9 a b c d e f g h i j k l m n o p q r s t u v w x y z}
      set hashLength [llength $hashSymbols]
      set hashUsed -1
    }

    incr hashUsed

    set keyToHash($key) [lindex $hashSymbols [expr $hashUsed % $hashLength]]
    for {set value [expr $hashUsed / $hashLength]} {$value != 0} {set value [expr $value / $hashLength]} {
      append keyToHash($key) [lindex $hashSymbols [expr $value % $hashLength]]
    } 
  }
  return $keyToHash($key)
}

namespace eval info {
  variable keys

  global files

  foreach file $files {
    source [file join $::dbDir $file]
  }

  variable sorter

  foreach key $keys {
    variable $key
    if { ! [info exists ${key}(Sort_Key)]} {
      puts stderr "$key does not have a Sort_Key entry"
      continue;
    }
    lappend sorter([set ${key}(Sort_Key)]) $key
  }

  variable sortedKeys

  foreach name [lsort [array names sorter]] {eval lappend sortedKeys $sorter($name)}

  if { ! [info exists sortedKeys]} {
    puts stderr "No keys in resorted list!"
    return
  }

  variable keyMap
  foreach letter1 {a b c d e f g h i j k l m n o p q r s t u v x w y z} {
    foreach letter2 {a b c d e f g h i j k l m n o p q r s t u v x w y z} {
      lappend keyMap "$letter1$letter2"
    }
  }

  variable seen

  foreach key $sortedKeys {
   variable $key
   set value [set ${key}(Sort_Key)]
   if { [info exists seen($value)] } {
     set ${key}(Sort_Key) "$value [lindex $keyMap $seen($value)]"
     incr seen($value)
   } else {
     set seen($value) 0
   }
  }

  variable keyHash
  foreach key $keys {
    set keyHash($key) 1
  }

  variable keys [lsort [array names keyHash]]

  proc sortKey {key} {
    variable $key
    return [set ${key}(Sort_Key)]
  }

  proc qExists {key} {
    variable $key
    return [info exists $key]
  }
}

namespace eval calc {
  variable binaryOps "+ - * /"
  variable unaryFunc "sin cos abs sqrt log"
  variable binaryFunc "min max"

  proc funcName {name} {
    if {$name == "min"} {return "least"}
    if {$name == "max"} {return "greatest"}
    return $name
  }

  proc parse {expr} {
    variable timeStack ""
    variable stack ""
    variable binaryOps
    variable binaryFunc
    variable unaryFunc

    foreach item $expr {
      if {![catch "expr $item * 1"]} { # A number
        lappend stack $item
      } elseif {[lsearch -exact $binaryOps $item] != -1} {
        set arg2 [lindex $stack end]
        set arg1 [lindex $stack end-1]
        set stack [lrange $stack 0 end-2]
        if {[llength $arg1] != 1} {set arg1 "($arg1)"}
        if {[llength $arg2] != 1} {set arg2 "($arg2)"}
        lappend stack "$arg1 $item $arg2"
      } elseif {[lsearch -exact $unaryFunc $item] != -1} {
        set arg1 [lindex $stack end]
        lappend stack "[funcName $item]($arg1)"
        set stack [lrange $stack 0 end-1]
      } elseif {[lsearch -exact $binaryFunc $item] != -1} {
        set arg2 [lindex $stack end]
        set arg1 [lindex $stack end-1]
        set stack [lrange $stack 0 end-2]
        lappend stack "[funcName $item]($arg1, $arg2)"
      } else {
        if {[llength [set parts [split $item "("]]] == 2} {
          set key [lindex $parts 0]
          set type [lindex [split [lindex $parts 1] ")"] 0]
          if {[info::qExists $key] && $type != ""} {
            set hash [hashValue $key]
            set name "${hash}::${key}::$type"
            lappend stack $name
            lappend timeStack $name
            continue;
          }
        }
        puts stderr "ERROR rewriting calculation '$expr'"
        puts stderr "Unrecognized item $item"
        exit 1
      }
    }
    if {[llength $stack] != 1} {
      puts stderr "ERROR rewriting calculation '$expr'"
      puts stderr "Stack is '$stack'"
      exit 1
    }
  }
}

namespace eval process {
  variable exclude {env colInfo remap tcl_platform keyToHash}
  variable xlat {db_name merged_dbs}
  variable remap

  set remap(character) Nature
  set remap(page_#) PageNumber
  set remap(run_#) RunNumber
  set remap(station_#) StationNumber
  set remap(calculate_result) calc_type

  variable colInfo

  set colInfo(approved) {text comment 'Record was seen and approved'}
  set colInfo(randomKey) {text comment 'Secret code for approval'}
  set colInfo(calculate_result) {text comment 'Type of information generated for derived information'}
  set colInfo(calc_expr) {text comment 'Expression for calculating derived information value'}
  set colInfo(calc_notes) {text comment 'Notes about calculation'}
  set colInfo(calc_time) {text comment 'Expression for calculating derived information time stamp'}
  set colInfo(cfs_to_gauge_converter) {text comment 'Which type of converter to use for extracting information from rating tables'}
  set colInfo(cfs_to_gauge_data) {text comment 'Name of rating table'}
  set colInfo(character) {text comment 'Character of river segment'}
  set colInfo(class) {text comment 'River classification, 1-6'}
  set colInfo(class_flow) {text comment 'Level dependent river classification'}
  set colInfo(date) {timestamp comment 'Modification time'}
  set colInfo(data_source) {text}
  set colInfo(db_name) {text}
  set colInfo(db_source) {text}
  set colInfo(description) {text comment 'Description of river segment'}
  set colInfo(difficulties) {text comment 'Difficulties encountered on this section'}
  set colInfo(display_name) {text comment 'Name displayed for this section'}
  set colInfo(drainage) {text comment 'Which drainage is this section in?'}
  set colInfo(drainage_area) {text comment 'Area of this drainage'}
  set colInfo(elevation) {text comment 'Altitude of gauge'}
  set colInfo(elevation_lost) {text comment 'Feet lost in this section'}
  set colInfo(email) {text comment 'E-Mail address of person who changed the record'}
  set colInfo(features) {text comment 'Interesting features on this segment'}
  set colInfo(gauge_location) {text comment 'Location of gauge'}
  set colInfo(gradient) {text comment 'Feet/Mile for this segment'}
  set colInfo(guide_book) {text comment 'Guide book reference'}
  set colInfo(high_flow) {text comment 'High flow level'}
  set colInfo(low_flow) {text comment 'Low flow level'}
  set colInfo(optimal_flow) {text comment 'Optimal level for running this segment'}
  set colInfo(bank_full) {text comment 'Bank full level for this segment'}
  set colInfo(flood_stage) {text comment 'Flood stage for this segment'}
  set colInfo(latitude) {text comment 'Latitude of segment'}
  set colInfo(longitude) {text comment 'Longitude of segment'}
  set colInfo(length) {text comment 'Length of segment in miles'}
  set colInfo(map_name) {text comment 'Name of map file for this record'}
  set colInfo(merged_dbs) {text comment 'databases used to construct this gauge'}
  set colInfo(name) {text comment 'Name of person who changed the record'}
  set colInfo(no_show) {text comment 'Do not display this record'}
  set colInfo(notes) {text comment 'Notes describing this section'}
  set colInfo(page_#) {text comment 'Guide book page number'}
  set colInfo(region) {text comment 'Region within a state this section is in'}
  set colInfo(remoteness) {text comment 'How remote is this section'}
  set colInfo(river_name) {text comment 'Name to display for the river name for this section'}
  set colInfo(run_#) {text comment 'Run number in guide book'}
  set colInfo(scenery) {text comment 'Type of scenery on this section'}
  set colInfo(season) {text comment 'Which season is the section runable'}
  set colInfo(section) {text comment 'Section name for this record'}
  set colInfo(sort_key) {text comment 'How to sort this entry'}
  set colInfo(source_name) {text comment 'Data source name'}
  set colInfo(state) {text comment 'State(s) this segment is located in'}
  set colInfo(station_#) {text comment 'USGS Station ID number'}
  set colInfo(geos_id) {text comment 'GEOS gauge ID'}
  set colInfo(usgs_id) {text comment 'USGS gauge ID number'}
  set colInfo(nwsli_id) {text comment 'NWS gauge ID'}
  set colInfo(cbtt_id) {text comment 'CBTT gauge ID'}
  set colInfo(nws_id) {text comment 'NWS(from CBTT) gauge ID'}
  set colInfo(snotel_id) {text comment 'SNOTEL gauge ID'}
  set colInfo(userName) {text comment 'Username of person who edited this entry'}
  set colInfo(watershed_type) {text comment 'Type of watershed'}

  proc colName {name} {
    variable remap
    if {[info exists remap($name)]} {return $remap($name)}
    return $name
  }

  proc colDefinitions {fp} {
    variable colInfo

    foreach field [lsort [array names colInfo]] {
      set name $field
      set name [process::colName $field]
      puts $fp " , $name $colInfo($field)"
    }
  }

  proc File {filename table mergedMaster} {
    variable colInfo
    variable exclude
    variable xlat
  
    if {[info exists keys]} {unset keys}
    source [file join $::dbDir $filename]
  
    set keys [info vars]
    
    foreach key $keys {
      if {[lsearch $exclude $key] != -1} continue
      upvar 0 $key a
      if {![array exists a]} continue
      set values ""
      set columns ""
      set delim ""
      foreach field [array names a] {
        if {$a($field) == ""} continue;
        set name [string tolower $field];
        if {[info exists colInfo($name)]} {
          set name [colName $name]
          if {$field == "date"} { 
            set seconds [clock scan "$a($field)"]
            set a($field) [clock format $seconds -format "%Y%m%d%H%M%S"]
          } elseif {$name == "class_flow"} {
            set a($field) [join $a($field) ","]
          } elseif {$name == "sort_key"} {
	    set a($field) [info::sortKey $key]
	  }
 
          if {[string match "*_flow" $name]} {
            regsub -all "\[']" $a($field) "ft" a($field)
          }

          if {[lsearch $xlat $name] != -1} { 
            regsub -all "\[\.-]" $a($field) "_" a($field)
          }
          regsub -all "'" $a($field) "" value
          append values "$delim'$value'"
          set delim ", "
          lappend columns $name
        } elseif {$name == "calculation"} {
          calc::parse $a($field)
          set time $calc::timeStack
          set expr "round(greatest(0, [lindex $calc::stack 0]))"
          append values "$delim'$time', '$expr'"
          set delim ", "
          lappend columns calc_time calc_expr
        } else {
          puts stderr "Unrecognized column name ${field}($name), found for key $key in file $filename"
          exit 1
        }
      }
      if {$columns != ""} {
        set hash [hashValue $key]
        puts "insert into $table (HashValue, Approved, [join $columns ","]) values ('$hash', '1', $values)"
	puts " on duplicate key update"
	set delim ""
	foreach col $columns {
          puts "  $delim$col=values($col)"
          set delim ","
        }
        puts ";"

        if {$mergedMaster != ""} {
          puts "insert into $mergedMaster (HashValue, [join $columns ","]) values ('$hash', $values)"
          puts " on duplicate key update"
          set delim ""
          foreach col $columns {
            puts "  $delim$col=values($col)"
            set delim ","
          }
          puts ";"
        }
      }
      unset $key
    }
  }
}

set dbName "levels_information"
set masterName "Master"
set correctionName "Corrections"
set mergedMaster "MergedMaster"

puts "create database if not exists $dbName;"
puts "use $dbName;"
puts ""

# First create the corrections table, then model others on it

puts "drop table if exists $correctionName;"
puts "create table $correctionName" 
puts " (HashValue varchar(8) comment 'My hash value for this entry'"
process::colDefinitions stdout
puts " ) "
puts " comment 'Corrections records for master table'"
puts ";"
puts ""

puts "drop table if exists $masterName;"
puts "create table $masterName like $correctionName;" 
puts "alter table $masterName change HashValue HashValue varchar(8) key;"
puts "alter table $masterName comment 'Master river information';"
puts ""

puts "drop table if exists $mergedMaster;"
puts "create table $mergedMaster like $masterName;" 
puts "alter table $masterName comment 'Merged version of master river information';"
puts ""


foreach file [lrange $files 0 end-1] {
  puts ""
  puts "# Handling $file"
  puts ""
  process::File $file $masterName ""
}

puts ""
puts "# Copy master into merged"
puts ""
puts "insert into $mergedMaster select * from $masterName;"


puts ""
puts "# Handling [lindex $files end]"
puts ""

process::File [lindex $files end] $correctionName $mergedMaster
