#! /bin/bash
#
# Replace the parameters table in mysql
#
# Pipe through mysql

DB=levels_information
TABLE=Parameters

ROOTDIR=$HOME/kayaking
PAGEDIR=$HOME/public_html

insert="insert into $TABLE values"

cat <<EOI
create database if not exists $DB;
use $DB;

drop table if exists $TABLE;

create table $TABLE (ident varchar(128) key comment 'Name', value text comment 'Value') comment 'Parameters';

$insert ('rootDir', '$ROOTDIR');
$insert ('webPageDir', '$PAGEDIR');
$insert ('templateDir', 'web.templates');
$insert ('mapSourceDir', 'maps');

$insert ('web.pre.filename', 'levels.head');
$insert ('web.post.filename', 'levels.tail');

$insert ('guide.pre.filename', 'description.head');
$insert ('guide.post.filename', 'description.tail');

$insert ('gage.html.pre.filename', 'gage.html.head');
$insert ('gage.html.post.filename', 'gage.html.tail');

$insert ('displayCGI', 'cgi/display');

$insert ('files.csv.suffix', '.csv');
$insert ('files.text.suffix', '.text');

$insert ('files.html.suffix', '.html');
$insert ('files.html.pre.filename', 'html.head');
$insert ('files.html.post.filename', 'html.tail');

select * from $TABLE;
EOI
