#! /bin/bash
#
# Define users and passwords
#
# Pipe into mysql to actually do it

host=mysql.wkcc.org
user=levels
passwd=Deschutes

for db in levels_information levels_data levels_page; do
  echo "drop database if exists $db;"
  echo "create database $db;"
  echo "grant all on $db.* to '$user'@'$host' identified by '$passwd';"
done

echo "flush privileges;"
