"""Initial schema with 18 tables

Revision ID: 58db118f1478
Revises: 
Create Date: 2026-03-01 11:58:13.212151
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '58db118f1478'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'latest_observation', type_='foreignkey')
    op.create_foreign_key(None, 'latest_observation', 'source', ['source_id'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_observation_source_type_time', 'observation', ['source_id', 'data_type', 'observed_at'], unique=False)
    op.drop_constraint(None, 'observation', type_='foreignkey')
    op.create_foreign_key(None, 'observation', 'source', ['source_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'observation', type_='foreignkey')
    op.create_foreign_key(None, 'observation', 'source', ['source_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_observation_source_type_time', table_name='observation')
    op.drop_constraint(None, 'latest_observation', type_='foreignkey')
    op.create_foreign_key(None, 'latest_observation', 'source', ['source_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
