#!/usr/bin/env python3
"""Emit a SQL migration that backfills reach.max_gradient and
reach.gradient_profile from a locally-populated DB.

The output is a per-row ``UPDATE reach SET … WHERE id = ?`` migration
matching the style of 0042-0044. It's idempotent (same input → same
output, no-op on re-run) so it can land safely on a prod DB that already
ran an earlier copy.

Usage::

    KAYAK_DB=/path/to/kayak.db python3 docs/one-offs/emit_max_gradient_migration.py \\
        --out data/db/migrations/0046_reach_max_gradient_backfill.sql

    # or pass --db /path explicitly. No hardcoded default — the script
    # exits with an error if neither --db nor KAYAK_DB is provided so a
    # mis-targeted machine fails loud instead of operating on the wrong DB.

Only emits rows where ``max_gradient IS NOT NULL OR gradient_profile IS NOT
NULL`` — rows the local DB still has as NULL stay NULL on prod.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sqlite3
import sys
from pathlib import Path

DEFAULT_DB = os.environ.get("KAYAK_DB", "")


def _sql_quote_text(s: str) -> str:
    """Quote a string for SQL: wrap in single quotes, double internal ones."""
    return "'" + s.replace("'", "''") + "'"


def _sql_value(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, str):
        return _sql_quote_text(v)
    raise TypeError(f"can't serialize {type(v).__name__}: {v!r}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db", default=DEFAULT_DB)
    ap.add_argument(
        "--out",
        default="data/db/migrations/0046_reach_max_gradient_backfill.sql",
    )
    args = ap.parse_args()
    if not args.db:
        sys.exit("error: pass --db /path/to/kayak.db or set KAYAK_DB in env")

    db_path = Path(args.db)
    conn = sqlite3.connect(args.db)
    conn.row_factory = sqlite3.Row

    rows = conn.execute(
        """
        SELECT id, aw_id, display_name, max_gradient, gradient_profile
        FROM reach
        WHERE max_gradient IS NOT NULL OR gradient_profile IS NOT NULL
        ORDER BY id
        """
    ).fetchall()

    print(f"Emitting backfill for {len(rows)} reach row(s) from {db_path}")

    # Source-DB hash so the migration's provenance is reproducible
    h = hashlib.sha256()
    h.update(db_path.read_bytes()[:1_000_000])  # first 1 MiB is plenty for fingerprinting
    db_fingerprint = h.hexdigest()[:16]

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append("-- Migration 0046: backfill reach.max_gradient + reach.gradient_profile")
    lines.append("-- @no_transaction")
    lines.append("--")
    lines.append("-- The @no_transaction marker routes through the runner's raw-cursor")
    lines.append("-- branch (src/kayak/cli/migrate.py:_wants_no_transaction). Required")
    lines.append("-- because gradient_profile JSON literals contain colons (e.g.")
    lines.append("-- '\"dl_mi\":0.2'), which SQLAlchemy text() interprets as bind-")
    lines.append("-- parameter placeholders — it sees ~40 phantom binds per UPDATE and")
    lines.append("-- raises InvalidRequestError. The raw-cursor path uses SQLite's real")
    lines.append("-- parser, which handles colons in string literals correctly, and")
    lines.append("-- honours this file's own BEGIN TRANSACTION/COMMIT pair below.")
    lines.append("--")
    lines.append("-- Generated by docs/one-offs/emit_max_gradient_migration.py from a local DB")
    lines.append(f"-- (source sha256[:16] of first 1 MiB: {db_fingerprint}).")
    lines.append("-- No wall-clock timestamp so a fresh regen against an unchanged DB")
    lines.append("-- is byte-identical to the committed file — drift on a `diff`")
    lines.append("-- means either the methodology changed or the local DB drifted.")
    lines.append("--")
    lines.append("-- Idempotent: re-running this migration on a DB whose values already")
    lines.append("-- match yields no-op UPDATEs. Values come from Phase 2 of the")
    lines.append("-- max_gradient + statistically-binned gradient profile work; see the")
    lines.append("-- companion plan/PR for methodology (3 sigma noise floor, adaptive 0.25-5 mi")
    lines.append("-- window, 0.05 mi sample density, mixed 1/3 arc-second + 1 m DEM).")
    lines.append("--")
    lines.append("-- The reach.gradient_profile column itself was added by migration 0045.")
    lines.append(
        f"-- This migration touches {len(rows)} of "
        f"{conn.execute('SELECT COUNT(*) FROM reach').fetchone()[0]} "
        f"reach rows."
    )
    lines.append("")
    lines.append("BEGIN TRANSACTION;")
    lines.append("")

    for r in rows:
        max_g = _sql_value(r["max_gradient"])
        prof = _sql_value(r["gradient_profile"])
        rid = r["id"]
        aw = r["aw_id"]
        name = (r["display_name"] or "").replace("\n", " ")
        if len(name) > 50:
            name = name[:47] + "..."
        comment = f"-- reach {rid}"
        if aw:
            comment += f" (aw_{aw})"
        if name:
            comment += f": {name}"
        lines.append(comment)
        lines.append(
            f"UPDATE reach SET max_gradient = {max_g}, gradient_profile = {prof} WHERE id = {rid};"
        )

    lines.append("")
    lines.append("COMMIT;")
    lines.append("")

    out_path.write_text("\n".join(lines))
    size_mb = out_path.stat().st_size / (1024**2)
    print(f"Wrote {out_path} ({size_mb:.2f} MiB, {len(rows)} UPDATEs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
