"""Render the paired-release cutover systemd drop-ins from ``HostConfig`` (4C).

Each **engine consumer** — the units that run ``levels …`` from the venv — gets a
``<unit>.service.d/cutover.conf`` drop-in that re-points ``ExecStart`` at the
release venv and overrides the paths that move off the (now immutable) install
root onto the persistent home / shared cache. The repo-shell-script consumers and
the host-level units are NOT re-pointed (they don't run the venv); see
``docs/PLAN_4c_renderers.md`` for the full classification.

Pure: ``HostConfig`` → text. The CLI wrapper (``levels render-units``) writes or
prints the result; ``systemd-analyze verify`` of the merged units happens on the
VM, not here.

Drop-in semantics that the templates rely on:
- ``ExecStart=`` (empty) RESETS the base unit's value; the next ``ExecStart=``
  sets the venv binary + the same subcommand/args. Without the reset, a oneshot
  would run both the old and new commands.
- ``ReadWritePaths=`` (empty) RESETS the accumulated list; the next assignment is
  the exact cutover writable set (e.g. the shared docroot replaces ``public_html``).
- ``Environment=`` assignments override the same key from the unit's
  ``EnvironmentFile=`` because the drop-in is merged after the base unit.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import PurePosixPath

from kayak.host import HostConfig

# The root config wrapper installs the secret-merged PHP config here; the
# deployer's KAYAK_RUNTIME_CONFIG defaults to the same path. PHP reads it (it's in
# open_basedir), so it's a fixed system location, not a per-host knob. MUST stay
# in lockstep with the deployer's KAYAK_RUNTIME_CONFIG: overriding one without the
# other points open_basedir at the wrong file and 500s PHP ([CONFIG-FATAL]) — if
# that path ever becomes configurable, both must read the same source (review #4).
RUNTIME_CONFIG_PATH = "/etc/kayak/runtime-config.json"


@dataclass(frozen=True)
class CutoverDropIn:
    """One engine consumer's rendered ``cutover.conf`` drop-in."""

    unit: str  # systemd unit, e.g. "kayak-pipeline.service"
    text: str  # the drop-in file content

    @property
    def path(self) -> str:
        """Install path relative to the systemd unit dir."""
        return f"{self.unit}.d/cutover.conf"


def _parent_dir(file_path: str) -> str:
    """The directory a file lives in — what ``ReadWritePaths=`` must grant."""
    return str(PurePosixPath(file_path).parent)


def render_cutover_dropins(h: HostConfig) -> list[CutoverDropIn]:
    """Render the cutover drop-in for every engine consumer, in install order.

    The six units that execute ``levels`` from the venv (the audit-gauges one
    joined this set when #191 promoted the source script to a subcommand).
    """
    venv = f"{h.release_root}/current/venv/bin/levels"
    current = f"{h.release_root}/current"
    dataset = f"{current}/dataset"
    db = f"{h.service_home}/DB"

    # (unit, ExecStart args after the binary, extra Environment=, ReadWritePaths)
    # DATASET_DIR is pinned to the RELEASE's snapshot on every unit (not the live
    # kayak_data clone) so a consumer always reads the dataset that shipped with
    # the running code; harmless on the units that don't read it.
    specs: list[tuple[str, list[str], dict[str, str], list[str]]] = [
        # pipeline builds the docroot → OUTPUT_DIR + the shared docroot RWP.
        ("kayak-pipeline", ["pipeline"], {"OUTPUT_DIR": h.docroot}, [h.docroot, db]),
        ("kayak-decimate", ["decimate"], {}, [db]),
        ("kayak-editor-retention", ["editor-retention"], {}, [db]),
        # fetch-osmb stages map layers into a dir the engine default resolves
        # relative to the install root → relocate to the persistent map-layers dir.
        (
            "kayak-fetch-osmb",
            ["fetch-osmb"],
            {"MAP_LAYERS_DIR": h.map_layers_dir},
            [h.map_layers_dir],
        ),
        # status writes its --output page (under the home, persists across releases).
        (
            "kayak-status",
            ["status", "--output", h.status_output],
            {},
            [_parent_dir(h.status_output)],
        ),
        # audit-gauges reads the DB + writes the gauge-metadata cache, which also
        # defaults relative to the install root → relocate it (same trap as #191).
        (
            "kayak-audit-gauges",
            ["audit-gauges", "--days", "16", "--email", "${AUDIT_EMAIL}"],
            {"GAUGE_METADATA_CACHE": h.gauge_metadata_cache},
            [db, _parent_dir(h.gauge_metadata_cache)],
        ),
    ]

    dropins: list[CutoverDropIn] = []
    for name, args, extra_env, write_paths in specs:
        env = {"DATASET_DIR": dataset, **extra_env}
        lines = [
            "# Generated by `levels render-units` (Batch 4C cutover). Do not edit;",
            "# re-render from host.yaml. See docs/PLAN_4c_renderers.md.",
            "[Service]",
            "ExecStart=",
            f"ExecStart={venv} {' '.join(args)}",
        ]
        lines += [f"Environment={k}={v}" for k, v in env.items()]
        lines.append(f"WorkingDirectory={current}")
        lines.append("ReadWritePaths=")
        lines.append(f"ReadWritePaths={' '.join(write_paths)}")
        dropins.append(CutoverDropIn(unit=f"{name}.service", text="\n".join(lines) + "\n"))
    return dropins


# --- serving config (nginx root + PHP-FPM open_basedir) ----------------------
# The cutover's only host-specific serving delta is the docroot path: nginx's
# `root` and the FPM `open_basedir` both move from the live `public_html` to the
# shared cache (`host.docroot` = the deployer's KAYAK_DOCROOT). Everything else
# (vhost server_names, the shared cert, the FPM socket/user) is static, committed
# config. Note the #3 docroot move dropped the `/opt/kayak/releases` open_basedir
# entry the pre-#3 design needed: the docroot is no longer inside the release, and
# `build` copies a self-contained PHP tree into it, so PHP never reads the release.


def render_nginx_root(h: HostConfig) -> str:
    """The nginx ``root`` directive for the served docroot.

    Replaces the hand-typed `root …;` in ``conf/snippets/levels-common.conf`` at
    cutover; the value is now derived from ``host.yaml`` deterministically.
    """
    return f"root {h.docroot};\n"


def render_fpm_open_basedir(h: HostConfig) -> str:
    """The PHP-FPM pool ``open_basedir`` directive — PHP's literal-path sandbox.

    The served docroot + the runtime data PHP reads (status cache, DB, logs) +
    the runtime-config file. ``open_basedir`` REPLACES (not extends) php.ini, so
    the list must be complete.
    """
    paths = [
        h.docroot,
        f"{h.service_home}/var",
        f"{h.service_home}/DB",
        f"{h.service_home}/logs",
        RUNTIME_CONFIG_PATH,
    ]
    return f"php_admin_value[open_basedir] = {':'.join(paths)}\n"
