"""Sanitization + validation for dataset regression content (S2).

Regression reports — a Markdown writeup, an SVG residual plot, and a JSON
fact-box per fit — are published to ``/static/regression/`` and served to
anonymous users. They are **dataset** content, so the engine must not trust
them:

* **Markdown** is rendered to HTML and sanitized with an explicit ``nh3``
  allowlist (raw HTML, event handlers, unsafe URL schemes, and external image
  sources are stripped) — never author-trust or CSP alone.
* **SVG** is parsed with ``defusedxml`` (no DTD / entities / external refs) and
  validated against a strict element/attribute allowlist, then **re-serialized**
  from the validated tree — a nonconforming SVG is rejected and a conforming one
  is never echoed verbatim (closes parser-differential gaps). SVG is treated as
  active same-origin content because the browser renders ``…/<slug>.svg`` as a
  document, outside the page CSP.
* **JSON** sidecars are size- and shape-checked (no ``NaN``/``Infinity``).

Used by both ``levels validate-dataset`` (reject nonconforming content before a
dataset is accepted) and ``levels build`` (render + sanitize before deploy).
Pure functions — no I/O.
"""

from __future__ import annotations

import json
import re
import xml.etree.ElementTree as ET

import defusedxml.ElementTree as DefusedET
import markdown as _markdown
import nh3


class UnsafeContentError(ValueError):
    """Regression content failed a security or shape check; it must not be served."""


# Size caps — a sidecar fact-box is tiny; the largest current plot SVG is ~116 KB.
MAX_SIDECAR_BYTES = 64 * 1024
MAX_SVG_BYTES = 2 * 1024 * 1024

# A report file's stem must be a slug: the charset that ``calc_expression.provenance_slug``
# and PHP's ``gauge_detail.php`` key on. The build skips any regression file whose stem
# isn't one, so a stray/orphan file with HTML metacharacters in its NAME can never reach
# the generated page (e.g. ``evil</title><script>…</script>.md``).
SLUG_RE = re.compile(r"^[A-Za-z0-9_-]+$")


def is_safe_slug(stem: str) -> bool:
    """Whether a report-file stem is a safe slug (``[A-Za-z0-9_-]+``)."""
    return bool(SLUG_RE.match(stem))


# --------------------------------------------------------------------------- #
# Markdown → sanitized HTML
# --------------------------------------------------------------------------- #

# H2 sections cut from the PUBLIC render (kept in the source-of-truth .md).
# Public viewers reaching the page via the "Full analysis →" link want the fit +
# diagnostics, not the maintainer scaffolding.
_HTML_DROP_SECTIONS: tuple[str, ...] = (
    "## SQL stub",  # pre-redesign reports (immutable history)
    "## `calc_expression` row",  # current reports (kayak_data CSV flow)
    "## Future",
)

# Tags the rendered report HTML may contain. python-markdown (tables +
# fenced_code) emits headings, paragraphs, lists, tables, code, blockquotes,
# links, and images; sub/sup are allowed for future superscript/subscript markup.
_NH3_TAGS: set[str] = {
    "h1", "h2", "h3", "h4", "h5", "h6", "p", "br", "hr",
    "ul", "ol", "li", "dl", "dt", "dd",
    "table", "thead", "tbody", "tr", "th", "td",
    "strong", "em", "b", "i", "code", "pre", "blockquote",
    "a", "img", "span", "sub", "sup",
}  # fmt: skip
_NH3_ATTRS: dict[str, set[str]] = {
    "a": {"href", "title"},
    "img": {"src", "alt", "width", "height", "title"},
    "th": {"align"},
    "td": {"align"},
}
# href schemes: http(s) + relative (nh3 permits relative URLs regardless). This
# strips javascript:/data:/etc. `img src` is constrained further below.
_NH3_URL_SCHEMES: set[str] = {"http", "https"}


def _filter_regression_md_for_html(md_text: str) -> str:
    """Drop maintainer-only content before rendering to public HTML.

    The markdown file is the source of truth and keeps every section; this trims
    it for the public page. Two things get cut:

    - Any H2 section whose heading starts with one of :data:`_HTML_DROP_SECTIONS`.
      The cut runs from the matching ``## `` line until the next ``## `` line or
      EOF, so non-dropped sections after a dropped one survive.
    - The top-of-doc ``Generated by:`` preamble plus the fenced code block that
      follows it (the reproduce command — useful to the next maintainer, noise on
      the public page).

    Sibling cross-links point at ``.md`` in the source (correct for in-repo
    viewing); the published site serves each report as ``.html``, so rewrite
    ``](./slug.md)`` → ``](./slug.html)`` so those links resolve.
    """
    out: list[str] = []
    dropping_section = False
    dropping_until_close_fence = False
    saw_open_fence = False
    for line in md_text.split("\n"):
        if dropping_until_close_fence:
            if line.startswith("```"):
                if saw_open_fence:
                    dropping_until_close_fence = False
                    saw_open_fence = False
                else:
                    saw_open_fence = True
            continue
        if line.startswith("## "):
            dropping_section = any(line.startswith(h) for h in _HTML_DROP_SECTIONS)
        if dropping_section:
            continue
        if line.startswith("Generated by:"):
            dropping_until_close_fence = True
            saw_open_fence = False
            continue
        out.append(line)
    rendered = "\n".join(out)
    return re.sub(r"\]\(\./([\w-]+)\.md\)", r"](./\1.html)", rendered)


def _is_local_ref(value: str) -> bool:
    """True for a same-directory relative ref (``./slug.svg`` / ``slug.svg``).

    Rejects anything absolute, protocol-relative, scheme-bearing, or escaping the
    directory — so a report image can only load a sibling artifact, never an
    external (tracking) URL.
    """
    v = value.strip()
    if not v or v.startswith(("/", "#")) or v.startswith("//"):
        return False
    if ".." in v:
        return False
    first_segment = v.split("/", 1)[0]
    return ":" not in first_segment  # no scheme (http:, javascript:, data:, …)


def _img_src_local_only(tag: str, attr: str, value: str) -> str | None:
    """nh3 ``attribute_filter``: drop a non-local ``img@src`` (keep everything else).

    Returning ``None`` removes the attribute, leaving a sourceless ``<img alt=…>``
    rather than a request to an external host.
    """
    if tag == "img" and attr == "src" and not _is_local_ref(value):
        return None
    return value


def render_markdown_safe(md_text: str) -> str:
    """Render a regression report's Markdown to a sanitized HTML fragment.

    Filters maintainer sections, renders via python-markdown (tables +
    fenced_code), then ``nh3.clean`` to the allowlist — stripping raw HTML,
    event handlers, disallowed URL schemes, and external image sources. Pure.
    """
    filtered = _filter_regression_md_for_html(md_text)
    html = _markdown.markdown(filtered, extensions=["tables", "fenced_code"])
    return nh3.clean(
        html,
        tags=_NH3_TAGS,
        attributes=_NH3_ATTRS,
        url_schemes=_NH3_URL_SCHEMES,
        link_rel="noopener noreferrer nofollow",
        attribute_filter=_img_src_local_only,
        strip_comments=True,
    )


# --------------------------------------------------------------------------- #
# SVG validation
# --------------------------------------------------------------------------- #

_SVG_NS = "http://www.w3.org/2000/svg"
# So ET.tostring emits a clean default-namespaced `<svg xmlns="…">` rather than
# `<ns0:svg xmlns:ns0="…">`. register_namespace is process-global + idempotent.
ET.register_namespace("", _SVG_NS)

# Presentation-only elements a generated residual plot uses (defs/clipPath/
# gradient/stop are allowed for future plots that clip or shade a region).
_SVG_TAGS: set[str] = {
    "svg", "g", "title", "desc", "rect", "circle", "ellipse", "line",
    "polyline", "polygon", "path", "text", "tspan",
    "defs", "clipPath", "linearGradient", "stop",
}  # fmt: skip
# Presentation-only attributes (geometry + styling). No href/xlink:href/style,
# no event handlers — those are rejected outright below.
_SVG_ATTRS: set[str] = {
    "x", "y", "x1", "y1", "x2", "y2", "cx", "cy", "r", "rx", "ry",
    "width", "height", "d", "points", "viewBox", "transform",
    "fill", "stroke", "stroke-width", "stroke-dasharray", "stroke-linecap",
    "stroke-linejoin", "opacity", "fill-opacity", "stroke-opacity",
    "font-family", "font-size", "font-weight", "text-anchor",
    "dominant-baseline", "class", "id", "clip-path", "clip-rule",
    "offset", "stop-color", "stop-opacity", "gradientUnits", "xmlns",
}  # fmt: skip
# A paint value may only reference a same-document fragment, e.g. url(#clip0).
# Case-insensitive: CSS function names are case-insensitive (so `URL(` is the
# same as `url(`).
_LOCAL_URL_FUNC = re.compile(r"(?i)^url\(\s*#[\w.:-]+\s*\)$")
# Resource-fetching CSS functions that could pull an EXTERNAL reference from a
# paint/clip attribute (url()/image()/image-set()/element()). Case-insensitive —
# a bare `URL(` defeated a lowercase-only check. Color functions (rgb()/hsl()/…)
# are intentionally not listed; only same-document url(#id) is allowed through.
_RESOURCE_FUNC_RE = re.compile(r"(?i)(?:url|image-set|image|element)\s*\(")


def _localname(qualified: str) -> str:
    """Strip a ``{namespace}`` prefix from an ElementTree tag/attr name."""
    return qualified.split("}", 1)[1] if "}" in qualified else qualified


def _check_svg_attr(attr: str, val: str) -> None:
    """Reject a single SVG attribute that isn't a safe presentation attribute."""
    if "}" in attr:  # any namespaced attribute (xlink:href, etc.)
        raise UnsafeContentError(f"disallowed namespaced SVG attribute {attr!r}")
    lattr = _localname(attr)
    if lattr.startswith("on"):
        raise UnsafeContentError(f"disallowed event-handler attribute {lattr!r}")
    if lattr in ("href", "xlink:href", "style"):
        raise UnsafeContentError(f"disallowed SVG attribute {lattr!r}")
    if lattr not in _SVG_ATTRS:
        raise UnsafeContentError(f"disallowed SVG attribute {lattr!r}")
    # A backslash in a presentation-attribute value is a CSS escape (e.g. `\75rl(`
    # → `url(`) — a generated plot never needs one, and allowing it would let a
    # value obfuscate a resource function past the check below. Reject outright.
    if "\\" in val:
        raise UnsafeContentError(f"attribute {lattr!r} contains a backslash escape: {val!r}")
    if _RESOURCE_FUNC_RE.search(val) and not _LOCAL_URL_FUNC.match(val.strip()):
        raise UnsafeContentError(f"attribute {lattr!r} has a non-local resource reference: {val!r}")


def _check_svg_element(el: ET.Element) -> None:
    """Reject a single SVG element (and its attributes) that isn't on the allowlist.

    Elements are pinned to the SVG namespace (or no namespace): a foreign-namespace
    element whose localname happens to be allowlisted (e.g. ``<xhtml:rect>``) is
    rejected, closing a parser-differential.
    """
    if "}" in el.tag:
        ns = el.tag[1:].split("}", 1)[0]
        if ns != _SVG_NS:
            raise UnsafeContentError(f"disallowed element namespace {ns!r}")
    name = _localname(el.tag)
    if name not in _SVG_TAGS:
        raise UnsafeContentError(f"disallowed SVG element <{name}>")
    for attr, val in el.attrib.items():
        _check_svg_attr(attr, val)


def validate_svg(svg_text: str) -> str:
    """Validate an SVG against the allowlist; return the re-serialized canonical SVG.

    Raises :class:`UnsafeContentError` on oversize input, XXE/DTD/entity/external
    constructs (via ``defusedxml``), a disallowed element/attribute, any event
    handler or ``href``/``style``/namespaced attribute, or a ``url(...)`` value
    that is not a same-document ``url(#id)`` fragment. The returned string is
    serialized from the validated tree, so the bytes served are exactly the bytes
    validated (never the verbatim input).
    """
    if len(svg_text.encode("utf-8")) > MAX_SVG_BYTES:
        raise UnsafeContentError(f"SVG exceeds {MAX_SVG_BYTES} bytes")
    # Reject XML comments and processing instructions explicitly. ElementTree drops
    # them on parse — so they wouldn't reach the re-serialized output today — but the
    # "reject nonconforming" contract must not depend on that serializer detail (a PI
    # like `<?xml-stylesheet href="javascript:…"?>` should be flagged, not silently
    # dropped). A single leading `<?xml …?>` declaration is allowed. `<!` (DOCTYPE) is
    # already rejected by defusedxml's forbid_dtd. In well-formed XML `<` is escaped in
    # text/attributes, so `<?`/`<!--` only appear as a real PI/comment.
    body = svg_text.lstrip()
    # A real XML declaration is `<?xml` followed by whitespace (per the XML spec);
    # strip one leading occurrence. A PI target like `xml-stylesheet` has a `-`, not
    # whitespace, after `xml`, so it is NOT mistaken for the declaration and falls
    # through to the reject below.
    if re.match(r"<\?xml\s", body):
        decl_end = body.find("?>")
        body = body[decl_end + 2 :] if decl_end != -1 else ""
    if "<!--" in body or "<?" in body:
        raise UnsafeContentError("SVG contains a comment or processing instruction")
    try:
        root = DefusedET.fromstring(
            svg_text, forbid_dtd=True, forbid_entities=True, forbid_external=True
        )
    except Exception as exc:  # defused* exceptions + ParseError — all are rejections
        raise UnsafeContentError(f"SVG did not parse safely: {exc}") from exc

    if _localname(root.tag) != "svg":
        raise UnsafeContentError(f"root element must be <svg>, got <{_localname(root.tag)}>")

    for el in root.iter():
        _check_svg_element(el)

    return ET.tostring(root, encoding="unicode")


# --------------------------------------------------------------------------- #
# JSON sidecar validation
# --------------------------------------------------------------------------- #


def _reject_json_constant(name: str) -> object:
    raise UnsafeContentError(f"non-standard JSON constant {name!r}")


def validate_json_sidecar(json_text: str) -> None:
    """Validate a regression JSON fact-box (pair-linear OR leadlag schema).

    Enforces a size cap, rejects ``NaN``/``Infinity`` (which ``json.loads``
    accepts by default), requires a JSON object with a non-empty string ``slug``
    (the shared key of both schemas), and — kept deliberately loose so both the
    pair-linear and leadlag shapes pass — type-checks ``coefs``/``lags`` as lists
    when present. Raises :class:`UnsafeContentError` on any violation.
    """
    if len(json_text.encode("utf-8")) > MAX_SIDECAR_BYTES:
        raise UnsafeContentError(f"JSON sidecar exceeds {MAX_SIDECAR_BYTES} bytes")
    try:
        data = json.loads(json_text, parse_constant=_reject_json_constant)
    except (ValueError, json.JSONDecodeError) as exc:
        raise UnsafeContentError(f"JSON sidecar is not valid JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise UnsafeContentError("JSON sidecar must be a JSON object")
    slug = data.get("slug")
    if not isinstance(slug, str) or not slug:
        raise UnsafeContentError("JSON sidecar must have a non-empty string 'slug'")
    for list_key in ("coefs", "lags"):
        if list_key in data and not isinstance(data[list_key], list):
            raise UnsafeContentError(f"JSON sidecar {list_key!r} must be a list")
