#! /bin/bash
#
# Walk through everything to fetch and process data
#

BINDIR=/home/tpw/local/bin
PAGEDIR=/home/tpw/pages/
NICE='nice'

$NICE $BINDIR/mkMainPage # Build the main page if needed
$NICE $BINDIR/mkDescription # Build the description page if needed
$NICE $BINDIR/fetcher -o $PAGEDIR # Go out and fetch data, then store it in my databases
$NICE $BINDIR/calcRating # Apply ratings tables to the data
$NICE $BINDIR/merger # Merge data together
$NICE $BINDIR/calculator # Build synthetic gages
# $NICE $BINDIR/maps # Build maps
$NICE $BINDIR/builder # Put it all together
