#!/usr/bin/env bash
# Regenerate tests/fixtures/live_schema.sql from the live DB.
#
# The snapshot is the "expectation" side of the schema-parity test
# (tests/test_db/test_schema_parity.py): if a migration lands but the
# ORM model isn't updated, the regenerated snapshot diverges from
# `Base.metadata.create_all()` and the test fails.
#
# Run after every migration that touches structural shape (CREATE
# TABLE, ALTER TABLE ADD/DROP COLUMN, CREATE/DROP INDEX, FK rewire).
# Comment-only / data-only migrations don't need a regen.
#
# Excludes:
#   - schema_migrations table (bookkeeping; not part of the ORM)
#   - sqlite_autoindex_* indexes (auto-generated for UNIQUE/PK; not
#     stable across schema rewrites, but the introspection helper
#     normalises these anyway)

set -euo pipefail
cd "$(dirname "$0")/.."

DB="${SQLITE_PATH:-${HOME}/DB/kayak.db}"
OUT="tests/fixtures/live_schema.sql"

if [[ ! -r "$DB" ]]; then
    echo "ERR: live DB not readable at $DB" >&2
    exit 1
fi

mkdir -p "$(dirname "$OUT")"

# Pull CREATE TABLE/INDEX statements from sqlite_master directly so we
# can filter precisely on table name and emit a stable, dependency-
# ordered stream (tables before indexes; alphabetical within each).
# Filter out:
#   - schema_migrations table (bookkeeping; not part of the ORM)
#   - sqlite_stat1 / sqlite_stat4 (created by ANALYZE; not schema)
{
    echo "-- Auto-generated by scripts/regenerate_schema_snapshot.sh"
    echo "-- Snapshot of the live DB schema; checked in to gate schema/model parity."
    echo "-- Regenerate after structural migrations land. Do not edit by hand."
    echo "--"
    echo "-- Source: $DB"
    echo "-- Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo
    sqlite3 -bail -batch "$DB" <<'SQL'
SELECT sql || ';'
FROM sqlite_master
WHERE type = 'table'
  AND name NOT LIKE 'sqlite_%'
  AND name != 'schema_migrations'
  AND sql IS NOT NULL
ORDER BY name;
SELECT sql || ';'
FROM sqlite_master
WHERE type = 'index'
  AND name NOT LIKE 'sqlite_autoindex_%'
  AND sql IS NOT NULL
ORDER BY name;
SQL
    # SQLAlchemy's CREATE TABLE DDL emits a trailing space after each column
    # comma; strip it so the checked-in fixture stays clean under
    # `git diff --check` and doesn't churn whitespace on every regen.
} | sed 's/[[:space:]]*$//' > "$OUT"

echo "wrote $OUT ($(wc -l <"$OUT") lines)"
